### ISSUE TITLE
Can't render BOM page

### ISSUE THREAD

**Issue by filipefurtad0** [openfoodfoundation/openfoodnetwork#10978]
## Description

This should be fixed by https://github.com/openfoodfoundation/openfoodnetwork/pull/10952; opening this issue as a prod test to make sure it's handled, once v4.3.12 is deployed.

Reported here:
https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1686326659329589

BOM page hangs and does not load orders. The root cause seems to be the same as, see:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/647c8b82ded5750008fb49dd?filters[event.since]=30d&filters[error.status]=open&filters[app.release_stage][value]=staging&filters[app.release_stage][type]=ne

## Expected Behavior

BOM page should render.

## Actual Behaviour

BOM page hangs.

## Steps to Reproduce

So far unable to have variants on this state, in staging... If so, it should just be a matter of rendering the BOM page, to see the bug.

## Animated Gif/Screenshot

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/1ebf74a5-fb39-49f0-a826-621d8e03b4f3)

## Workaround

- None for editing orders with bulk items
- Regular orders can still be edited individually

## Your Environment

* Version used: v4.3.11
* Browser name and version: - 
* Operating System and version (desktop or mobile): -

**Comment by BethanOFN** [comment]
Fix not working for BOM and still hanging:
<img width="1440" alt="Screenshot 2023-06-12 at 12 34 31" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/100226210/422da33f-6f0c-47ff-aa2f-3526851cbf69">

Side note: fix has resolved the 'undefined method `downcase' for nil:NilClass\' error that was preventing access to  Order Cycle Supplier Reports through the API.

**Comment by filipefurtad0** [comment]
> fix has resolved the 'undefined method `downcase' for nil:NilClass' error that was preventing access to Order Cycle Supplier Reports through the API.

Hooray for this - thanks for double checking :pray: We'll investigate the BOM issue further.

**Comment by filipefurtad0** [comment]
Interesting that the API and BOM errors seems the same - Bugsnag groups them - but there are no occurrences on the last two hours on the BOM page:

![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/64a757d6-ca67-48f9-bc48-b02acd14cc78)

I'm not sure what to make of this yet...

**Comment by filipefurtad0** [comment]
> Maybe we have a performance issue?

This is my reading as well, as it looks like the error 500 is gone from Bugsnag. This may have made a (new?) performance issue visible... I'm wondering if this is new, or a regression.

**Comment by jibees** [comment]
> I'm wondering if this is new, or a regression.

Locally, I can't spot any differences between `4.3.11` and `4.3.12` (nor master)

**Comment by filipefurtad0** [comment]
Ok, since there are no new occurrences from `undefined method `downcase' for nil:NilClass` error I'd propose to close this and investigate an eventual performance issue elsewhere. Sounds good?

If we're having new/critical performance issues on the BOM page, then I guess we'd be getting timeouts, and such errors on Bugsnag...

**Comment by dacook** [comment]
Sorry.. but we can still produce the same `undefined method 'downcase' for nil:NilClass` error in AU, when editing a particular order: 
* https://openfoodnetwork.org.au/admin/orders/R142118266/edit
* https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/647c93c2b164c000084f119d

Fix https://github.com/openfoodfoundation/openfoodnetwork/pull/10952 doesn't directly touch the code where this error is caused, so I guess we need to go further. This seems pretty important, so I will pick this up today.

**Comment by dacook** [comment]
Please ignore last comment. It was fixed, but not yet deployed to au-prod. After deploying v4.3.12 we can see that this is now working.

**Comment by dacook** [comment]
I will close as it appears it is fixed for everyone.

**Comment by BethanOFN** [comment]
> 

BOM is still hanging for both large hub users and myself and cannot load page - @jibees were you accessing BOM from an account with big order volumes (e.g. mine has almost 200k orders)? Interestingly BOM page itself loads, but when trying to filter (e.g. to a specific hub), the page hangs and does not load. Without being able to apply filters/search orders though, the page is unusable. Screenshot of request still hanging after 4+ minutes
<img width="640" alt="Screenshot 2023-06-13 at 10 36 56" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/100226210/26957a9c-597e-414c-b8d6-df1de29f3fae">

**Comment by jibees** [comment]
I was trying on `https://openfoodnetwork.org.uk` ; and the screenshots I've done was from here. Am I right: is this the instance you use? It seems you're filtering on a Shop right? I will test it.
Regarding your screenshot, it seems we definitely suffering from performance issues, not sure this was introduced by the latest release, but we need to deep dive into, as it seems to be largely unusable. Will open an issue. 

##### Without filtering, it's too long (sum the time column)
<img width="1805" alt="Capture d’écran 2023-06-13 à 11 49 02" src="https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/4aad5dc2-5288-4cef-88de-5ebd8965cdce">

##### When filtering with a shop
Can't see any response... Taking too much time.
