### ISSUE TITLE
When two shopfronts are open in the same browser, very disturbing conflicts and false info displayed

### ISSUE THREAD

**Issue by myriamboure** [openfoodfoundation/openfoodnetwork#1172]
I open the shopfront of Ninety miles biodynamics, here is what I see:
![screenshot from 2016-09-26 13-08-10](https://cloud.githubusercontent.com/assets/8135376/18832200/4ce0fa4a-83ea-11e6-8524-5427f28e8aec.png)

Then in another tab, I open the shopfront of Hand to Ground, here is what I see:
![screenshot from 2016-09-26 13-06-14](https://cloud.githubusercontent.com/assets/8135376/18832208/60870e22-83ea-11e6-8682-bbd1c94f50bf.png)

As you see, the same products appear... then I close the Ninety miles shop page, and reload the Hand to ground page, here is what I see:
![screenshot from 2016-09-26 13-09-55](https://cloud.githubusercontent.com/assets/8135376/18832251/8eb36c00-83ea-11e6-88ce-78f09837cd78.png)
As you see now the good products are displayed in the shop.

I think it's a pretty common behavior to open various tabs to compare shops, etc, so it seems to be an issue.

Ping @mkllnk I don't know if that's only a problem in Aussie, have not tried yet in other instances.

**Comment by mkllnk** [comment]
This is a known issue. A user can work only on one shop front. The solution would be a lot of work since a lot of code relies on that global reference to the current shop. It would be great to have time and money to fix this.

**Comment by bingxie** [comment]
I opened few tabs of different shops, but I can't reproduce this issue on au website and my local machine. @sstead can you have a look and reproduce it?

**Comment by myriamboure** [comment]
I retested and the bug doesn't seem to happen anymore. The UX of shopping in two tabs is not ideal (error message a bit confusing) but it's ok for now and at least this issue is not anymore.  Tried as guest and logged in. Must have been fixed by some other thing :-)

**Comment by mkllnk** [comment]
I just saw the code causing this a few days ago. This problem still exists, but may be a bit difficult to re-produce. The problem is the following logic:

- User visits shop1.
- shop1 is stored as default shop for user.
- Products for the default shop are loaded into the shopfront of shop1.

Now if you open two shops at the same time, you can get a race condition:

- User visits shop1.
- User visits shop2.
- shop1 is stored as default shop for user.
- shop2 is stored as default shop for user.
- Products for the default shop (shop2) are loaded into the shopfront of shop1. :-1: 
- Products for the default shop (shop2) are loaded into the shopfront of shop2. :+1: 

You can see this bug only if you try to open two shops at the same time.

**Comment by myriamboure** [comment]
Ok, putting s3 because this situation is very unlikely... so let's keep it but fix later as we have other more urgent priorities.

**Comment by RachL** [comment]
After chatting with Lynne, we agree that OFN is not supporting shopping in multiple shops. If this comes up in support we can see how to prioritise. Closing.
