### ISSUE TITLE
Error when deleting an item from order #step6

### ISSUE THREAD

**Issue by enricostano** [openfoodfoundation/openfoodnetwork#1658]
This issue has been found by both @sstead and @sigmundpetersen  while testing https://github.com/openfoodfoundation/openfoodnetwork/pull/1524, more info [here](https://community.openfoodnetwork.org/t/spree-testing-june-2017/976).

In `admin/orders/R245886616/edit` you can delete specific line items by clicking on the trash bin icon located at the right end of each line and on `Ok` on the confirmation dialog.

As a result the line item has been deleted but since we get the `HTML` response from the controller for some weird reason it ends up rendered as a huge `.error` flash bar.

![](https://community.openfoodnetwork.org/uploads/default/original/1X/191ff149bfd9b0f728461c13220d312f0ef53dd1.png)

The issue has been introduced by https://github.com/openfoodfoundation/openfoodnetwork/commit/710c94b8f03313ee46a2ea1a19cc782e7cb39f62 and https://github.com/openfoodfoundation/openfoodnetwork/commit/a4bd8538f7161333280abfb27f66cee4496e4ea3

The questions here are:
 - do we still need HTML responses for `LineItemsController`?
 - is there any reason why we're not using the official API `/api/orders/:order_id/line_items/:id` for both `PUT` and `DELETE`?

As a context please look at a [this discussion](https://community.openfoodnetwork.org/t/road-map-for-ofns-api/931) about the future of APIs in OFN.

cc/ @RohanM @oeoeaio @sauloperez

**Comment by enricostano** [comment]
I created a [patch](https://gist.github.com/enricostano/400567d9ef99b9f8ce9d6b529c24c181) that solves this issue by always returning a JSON response... but we need to find an answer to the questions in the descritpion first.

**Comment by RohanM** [comment]
In response to 2 (why are we not using the official API), I believe the answer is that the Spree API is intended for external use, and so we're not using it on our own backend/frontend. I could be wrong though, it's a long time since I've worked on this code.

An alternative solution would be to modify the JS code to request `.json` endpoints, which would take us through the JS pathway already present in the controllers. I imagine that modifying the JS would be more difficult than the controllers, though, so up to you which solution to go with.

**Comment by kirstenalarsen** [comment]
just an outside question . . if we're making decisions about use of API etc, should we have a discussion about where we want to actually go with API (which will become more and more important) to shape how these changes are made? e.g. can we be doing it in a way that is improving API accessibility as we go? @RohanM @oeoeaio @mkllnk

**Comment by sauloperez** [comment]
I found the fix for this https://github.com/Em-AK/openfoodnetwork/pull/10. As you will see in depth there, we should have added a JS response and not a JSON one.

I suggest we move forward with it while we figure out later on whether we need to override that controller in the first place.

**Comment by enricostano** [comment]
I merged https://github.com/Em-AK/openfoodnetwork/issues/10 since it seems to us the quickest way to fix this issue, but we'll need to come back to that "multi format AJAX" problem in the future. Open issue here https://github.com/openfoodfoundation/openfoodnetwork/issues/1691

Now we can test this again to see if it has been actually fixed. Maybe @sstead or @sigmundpetersen can help with that once we deploy step 6 somewhere. Will ping you ASAP, thanks!

**Comment by enricostano** [comment]
@sstead @sigmundpetersen could you please test this again? Thanks!

It is deployed at https://staging1.openfood.com.au

cc/  @OliverUK

**Comment by sstead** [comment]
I'm still experiencing problems deleting items from orders, but the sequence of events has changed...
![image](https://user-images.githubusercontent.com/10843056/28447637-5c06da6a-6e15-11e7-9077-cab885a70033.png)

Another issue I spotted while testing this...
![image](https://user-images.githubusercontent.com/10843056/28447633-4ff1368a-6e15-11e7-89d0-98fc696311e2.png)

**Comment by sauloperez** [comment]
The problem is due to the fact that Spree only hides the deleted row once it's been deleted in the backend.

The hidden input id field for that line item it's still in the DOM and thus sent to the backend (among the other line items) when udpating the fees. The backend then simply fails because it can't find that same line item that it just removed.

**Comment by sauloperez** [comment]
It gets fixed by https://github.com/coopdevs/spree/pull/1. Once that gets merged we can upgrade to the latest spree fork commit.

**Comment by enricostano** [comment]
@sstead @sigmundpetersen could you please test this again? We deployed a fix in staging1. Thanks!

**Comment by sstead** [comment]
@enricostano This issue seems to be fixed :) I can successfully delete line items.

**Comment by enricostano** [comment]
Thanks @sstead for the help 🙏
