### ISSUE TITLE
Error when generating PDF invoice in OFN CA

### ISSUE THREAD

**Issue by kristinalim** [openfoodfoundation/openfoodnetwork#3784]
## Description

(I've actually already looked into this, but creating this issue to document. The issue might occur again in the future.)

From @tschumilas on Slack:

> BUT  -  I cannot print or send invoices.   I can resend confirmations -  but if i try to print or send an invoice,  I get the snail.    This was always working before - have printed dozens of invoices.

## Expected Behavior

Generating the invoice PDF succeeds.

## Actual Behaviour

Generating the invoice PDF fails.

## Steps to Reproduce

1. Go to an order in the admin section.
2. Under "Actions", click on "Print Invoice".
3. You get the HTTP 500 snail page.

## Context

See thread on Slack:
https://openfoodnetwork.slack.com/messages/C2GQ45KNU/convo/C2GQ45KNU-1556937130.070800/

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login

**Comment by kristinalim** [comment]
I saw errors like this in `log/production.log`:

```
Started GET "/admin/orders/ORDER_NUMBER/print" for IP_ADDRESS at 2019-05-03 20:36:17 -0400
Processing by Spree::Admin::OrdersController#print as HTML
  Parameters: {"authenticity_token"=>"AUTHENTICITY_TOKEN", "id"=>"ORDER_NUMBER"}
***************WICKED***************
  Rendered spree/shared/_line_item_name.html.haml (4.7ms)
  Rendered spree/admin/orders/_invoice_table.html.haml (26.4ms)
  Rendered spree/order_mailer/_payment.html.haml (7.5ms)
  Rendered spree/admin/orders/invoice.html.haml (46.2ms)
Completed 500 Internal Server Error in 92.3ms (ActiveRecord: 21.5ms)
Notifying https://notify.bugsnag.com of RuntimeError

RuntimeError (Bad wkhtmltopdf's path: `/` is not writable.
Bundler will use `/tmp/bundler/home/openfoodnetwork' as your home directory temporarily.
/home/openfoodnetwork/.gem/ruby/2.1.0/bin/wkhtmltopdf):
  app/controllers/spree/admin/orders_controller_decorator.rb:49:in `print'
```

In the Rails console:

```ruby
WickedPdf.config
=> {:exe_path=>"/home/openfoodnetwork/.gem/ruby/2.1.0/bin/wkhtmltopdf"}
```

The binary `/home/openfoodnetwork/.gem/ruby/2.1.0/bin/wkhtmltopdf` existed, but using that to create a sample PDF failed:

```
/home/openfoodnetwork/.gem/ruby/2.1.0/bin/wkhtmltopdf http://google.com google.com
```

The error above is a bit misleading, but I read that [errors could be misleading](https://github.com/mileszs/wicked_pdf/issues/758#issuecomment-411496362) if `WickedPDF` is not able to find the `wkhtmltopdf` binary. Running `which wkhtmltopdf` did not have any results. This file, which existed in OFN AU, did not exist in OFN CA, which suggests that installation of the gem was not successful: `/home/openfoodnetwork/.rbenv/shims/wkhtmltopdf`.

I reinstalled the `wkhtmltopdf-binary` gem and restarted Unicorn:

```
gem install wkhtmltopdf-binary -v 0.12.4 --verbose
service unicorn_openfoodnetwork restart
```

This is pending confirmation, but the following now works:

```
/home/openfoodnetwork/.gem/ruby/2.1.0/bin/wkhtmltopdf http://google.com google.com
```

Comparing with OFN AU helped.

**Comment by tschumilas** [comment]
just tried - still cannot print or send invoices

**Comment by kristinalim** [comment]
@tschumilas It should work now. I created a test hub in production, and then quickly closed the OC so it doesn't appear in the default list of hubs.

I had to stop and start the Unicorn process, as opposed to doing a simple restart.

**Comment by kristinalim** [comment]
@mkllnk Were there issues restarting Unicorn in AU using the `/etc/init.d/` script as well? As far as I understand, because `preload_app` is not set, restarting Unicorn should pick up changes in the app code, including gems... But it didn't seem to behave this way.

Something I noticed just now is that AU has `/etc/systemd/system/unicorn_openfoodnetwork.service` which CA doesn't have. This means the `service unicorn_openfoodnetwork` command in AU would prefer this script, while CA would use the one in `/etc/init.d/`.

**Comment by kristinalim** [comment]
#3480 is not exactly a duplicate, but the fix will most likely address both.

**Comment by tschumilas** [comment]
Thanks @kristinalim -  working perfectly

**Comment by kirstenalarsen** [comment]
reopening as @tschumilas is now experiencing the same problem again :(

**Comment by mkllnk** [comment]
I just fixed it again:
```
cd apps/openfoodnetwork/current/
gem install wkhtmltopdf-binary -v 0.12.4
/etc/init.d/unicorn_openfoodnetwork stop && sleep 5 && /etc/init.d/unicorn_openfoodnetwork start
# delayed job was working already
```

**Comment by luisramos0** [comment]
just for the record, I did this yesterday and it didnt fix the problem!

  492  gem install wkhtmltopdf-binary -v 0.12.4 --verbose
  493  service unicorn_openfoodnetwork
  494  service unicorn_openfoodnetwork stop
  495  service unicorn_openfoodnetwork start
  496  tail ../shared/log/unicorn.log
  497  date
  498  /home/openfoodnetwork/.gem/ruby/2.1.0/bin/wkhtmltopdf http://google.com google.com
  499  service unicorn_openfoodnetwork stop
  500  service unicorn_openfoodnetwork start
  501  history
