### ISSUE TITLE
Enterprise user should be able to delete line items and adjustments

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/openfoodnetwork#505]
![image](https://cloud.githubusercontent.com/assets/2911176/7218656/0cc131f2-e6be-11e4-855c-89de4e64c553.png)

**Comment by mkllnk** [comment]
Done in the branch single-order-patches.

**Comment by kirstenalarsen** [comment]
nope, still getting grumpy cat

i can now edit them as enterprise user, but still can't delete

![image](https://cloud.githubusercontent.com/assets/2911176/7529479/c551fe50-f57c-11e4-9165-5b7510314f94.png)

**Comment by mkllnk** [comment]
I was able to reproduce a similar error with Firefox on the staging server. It's the "done is not defined" thing. Have you been testing with Firefox?

**Comment by mkllnk** [comment]
Try again. I can't reproduce it any more. The uglifier might have done that.
