### ISSUE TITLE
Missing translation key for expired token

### ISSUE THREAD

**Issue by RachL** [openfoodfoundation/openfoodnetwork#5782]
## Description

When resetting their password, users are often ending up opening an old email with an expired reset link. This leads to an error which is not translated, so they don't understand what's wrong.

## Steps to Reproduce

1. Try to change your password with an expired link

## Animated Gif/Screenshot

![image.png](https://images.zenhubusercontent.com/595e669a61b4ca3b0a737135/033cb4de-e4dc-4ef9-9991-92202ffd5ef9)

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.9.10
* Browser name and version: Firefox 78
* Operating System and version (desktop or mobile): Desktop

**Comment by luisramos0** [comment]
I think we should ignore the problem in v2 and also in current v3 and look at what this looks like after the devise upgrade, that's where we should fix this, in this PR
https://github.com/openfoodfoundation/openfoodnetwork/pull/4084

**Comment by RachL** [comment]
Ok I'm adding the blocked label then

**Comment by psychoslave** [comment]
Hello,

Is the issue still relevant, especially regarding @luisramos0 remark on #4084 (which have been merged)?

**Comment by RachL** [comment]
The upgrade has been merged, so we can work on this issue now @psychoslave 👍

**Comment by psychoslave** [comment]
Related discussion: https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1622032753032700

**Comment by RachL** [comment]
@openfoodfoundation/core-devs I can't seem to reproduce this issue even with links I've generated in November... Could it be that those token do not expire at all now since the devise upgrade? Is that a good practice?

**Comment by jibees** [comment]
@RachL I'm not the best person to answer but regarding the code and the doc, I can almost confirm you that, you're right, there is no expire time configured.

Source:
https://www.rubydoc.info/github/heartcombo/devise/master/Devise/Models/Confirmable
https://github.com/jibees/openfoodnetwork/blob/master/config/initializers/devise.rb#L45-L52

**Comment by RachL** [comment]
thanks @jibees !

@psychoslave would you be willing to work on introducing an expiration time or is this too complex as a first issue?

thanks for choosing this one though :) It revealed a more important bug!

**Comment by jibees** [comment]
I just saw those three lines, worth a read, and to understand (specially how they interact with `confirm_within`) : 
https://github.com/jibees/openfoodnetwork/blob/master/config/initializers/devise.rb#L132-L135

**Comment by psychoslave** [comment]
@RachL introducing an expiration time :hourglass_flowing_sand:  would seem an interesting think to do actually. :smile: 

Should an other issue be opened?

**Comment by shveikus** [comment]
Hi everyone, I'm new to this project and due research for some tasks came across this issue. 
By the way, it is still relevant, for example, I've reproduced it on prod environment right now.

![image](https://user-images.githubusercontent.com/40833597/120291917-7bbc7f80-c2cc-11eb-939c-27ced5bb0e47.png)
I can share the reset link into DM if necessary)

Also, if it is required I can deeply dive into the issue if no one made it before now)

**Comment by RachL** [comment]
Hello @shveikus thanks for this feedback! Do you know how long you've waited between the click on the link and the time the email was sent?

**Comment by shveikus** [comment]
Yep, sure.
I received the message in about 1 minute.

I've generated (and received) the link on 26 May, 17.17. And checked it only today while looking through the mailbox.

**Comment by psychoslave** [comment]
Hello @shveikus nice to see you join the community.

If you join Slack too, we have a dedicated channels for new developers: https://openfoodnetwork.slack.com/archives/C023WTQUAMN

Thanks for the feedback on you experiment on the production server. :smile: 

By the way, I also started to tackle this issue a few days ago.

**Comment by psychoslave** [comment]
So I still wasn't able to reproduce the message appearance at will. I tried to set `reset_password_within = 2.seconds` in the following file:
- `$OFN_REPOSITORY/config/initializers/devise.rb` line 135
- `~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/devise-4.8.0/lib/devise.rb` line 200
- `~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/devise-4.8.0/lib/generators/templates/devise.rb` line 227
- `~/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/devise-token_authenticatable-1.1.0/spec/support/rails_app/config/initializers/devise.rb` line 135
- `~/.rbenv/versions/2.5.9/lib/ruby/gems/2.5.0/gems/devise-4.8.0/lib/devise.rb` line 200
- `~/.rbenv/versions/2.5.9/lib/ruby/gems/2.5.0/gems/devise-4.8.0/lib/generators/templates/devise.rb` line 227
- `~/.rbenv/versions/2.5.9/lib/ruby/gems/2.5.0/gems/devise-token_authenticatable-1.1.0/spec/support/rails_app/config/initializers/devise.rb` line 135

But this still doesn't achieve the expected result.

Expected result: asking for a new password reset, a new tab is opened with the email, after waiting for longer than two seconds, opening the reset password link should throw the error message.

Actual result: the form to type a new password is displayed, no error message.

**Comment by psychoslave** [comment]
Regarding the translation issue itself, I had a look at `./config/locales/en.yml`, and the matching keys are likely:
```yaml
 340   reset_password_token: Reset password token                                                                                                                                                                  
 341   expired: has expired, please request a new one 
```

Note that these keys are **not** under `en.devise`, but directly under `en.`. I don't know if it is important in this case.

Indeed it's seems to me that in my case the corresponding calling code would be in `~/.rbenv/versions/2.5.9/lib/ruby/gems/2.5.0/gems/devise-4.8.0/lib/devise/models/recoverable.rb`:155 :
```ruby
140         # Attempt to find a user by its reset_password_token to reset its                                                                                                                                      
141         # password. If a user is found and token is still valid, reset its password and automatically                                                                                                          
142         # try saving the record. If not user is found, returns a new user                                                                                                                                      
143         # containing an error in reset_password_token attribute.                                                                                                                                               
144         # Attributes must contain reset_password_token, password and confirmation                                                                                                                              
145         def reset_password_by_token(attributes = {})                                                                                                                                                           
146           original_token       = attributes[:reset_password_token]                                                                                                                                             
147           reset_password_token = Devise.token_generator.digest(self, :reset_password_token, original_token)                                                                                                    
148                                                                                                                                                                                                                
149           recoverable = find_or_initialize_with_error_by(:reset_password_token, reset_password_token)                                                                                                          
150                                                                                                                                                                                                                
151           if recoverable.persisted?                                                                                                                                                                            
152             if recoverable.reset_password_period_valid?                                                                                                                                                        
153               recoverable.reset_password(attributes[:password], attributes[:password_confirmation])                                                                                                            
154             else                                                                                                                                                                                               
155               recoverable.errors.add(:reset_password_token, :expired)                                                                                                                                          
156             end                                                                                                                                                                                                
157           end   
```

I'm not yet familiar with the `recoverable.errors.add` thing, so it will require more investigation on that track, if that doesn't prove to be a wrong trail.

By the way, having this kind of broken sentence is really an issue in itself to my mind, but that should be reported to Devise instead.

**Comment by shveikus** [comment]
@psychoslave, please sorry for the delay) 
After you forward the link - fill in some password into the form and only after that the message will be appeared)

IMHO, to resolve this issue we have to follow devise contributor's [advice](https://github.com/heartcombo/devise/wiki/I18n) and add gem [devise-i18n](https://github.com/tigrish/devise-i18n/tree/master).

If it is required, we can add locales manually (as an example from https://github.com/tigrish/devise-i18n/tree/master/rails/locales) and customize them. 

Tested locally, worked for me)
![image](https://user-images.githubusercontent.com/40833597/120942434-8f833e00-c731-11eb-8e9f-b6b6bdda9885.png)

**Comment by psychoslave** [comment]
Ok, thank you very much @shveikus for these precious hints. :pray: 

On a side note, I think that it would make more sense to show this message directly if the token is expired, possibly along a "send me a new one please" link. But that will be for an other issue. :wink:

**Comment by mkllnk** [comment]
Also note that you need to restart the application after changing an initializer because initializers are only executed at boot time. And if you use Spring, you may need to restart that as well before starting a new process.

Sometimes, if I wonder if my changed code is executed, I modify something really obvious and see if that's executed. For example adding `binding.pry` or `raise` give you a good indication if the code is actually run.

**Comment by RachL** [comment]
Hello @psychoslave all good on you side on this issue or is there anything we can do to help out?

**Comment by psychoslave** [comment]
Hello, everything seems good for me on this issue yes, I just have been busy on other activities lately :wink:

**Comment by psychoslave** [comment]
So, some moves from other issues impacted the work pertaining to this one. 

Notably, 
- the localization process evolved a bit, I updated the [wiki to reflect that](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Locale-and-sample-data)
- the `./script/delayed_job` was dropped, so emails won't popup anymore in new tabs.
  - as of now, I didn't found a way to gain access to the relevant reset password page, despite a tentative to forge myself the URI with the known token, see
    -  https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1625479538143400 
    - https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1625754993163000

**Comment by psychoslave** [comment]
Also, while it lead to erroneous pipeline, the forged URI for password reset generate a view with a partially untranslated message:
```
 Il y a eu un souci avec les champs suivants :
    Reset password token is invalid
```

Generating all Devise-i18n locales to inspect it with `rails g devise:i18n:locale en`, it happens that this string is not available there. 

Having a look at `devise-4.8.0/lib/devise/models/recoverable.rb` again, it seems that the code generates the yaml key entry along it's algorithm. I'll need to dig further, but maybe that's a key among all the possible combination that the algorithm can generate this one was never taken into account.

**Comment by psychoslave** [comment]
@shveikus did you made any additional step in your test? As I can find a way to the correct URL with an expired token right now (due to reasons explained just above), I am unable to test the case for which you kindly provided a screenshot.

**Comment by mkllnk** [comment]
- DelayedJob got replaced by Sidekiq.
- You can run `bundle exec sidekiq -q mailers -q default` or use Foreman.

**Comment by psychoslave** [comment]
So, I was finally able to reproduce the bug, as well as a result identical to the one given by @shveikus previously. That said, I don't think that an half translated string is something fine. Indeed, currently the string displayed (with French as locale) is `Reset password token est expiré, veuillez en demander un autre`.

Some additional work will be necessary before this lead to something fine. The string should aim something like  `Le jeton de réinitialisation du mot-de-passe est expiré, veuillez en demander un autre`.

**Comment by RachL** [comment]
Hello @psychoslave how are you doing on this one? If I understand there a piece which depends on devise. Shall we move on with a translating what's on OFN side in the meantime?

**Comment by psychoslave** [comment]
Hello. Well, we might already translate what is translatable indeed, but it might still result in half translated string I guess.

**Comment by RachL** [comment]
@psychoslave yes, but as the rest is on devise side, we can do it separately?

**Comment by RachL** [comment]
@psychoslave as we have not much news here I'm unassigning you so that someone else can have a look. If you still want to work on it don't hesitate to comment :)

**Comment by psychoslave** [comment]
Hi everyone, I've been busy on other projects, and probably won't have much time to dedicate to OFN in the near future, so good luck with this specific issue, and I hope I'll be able to help here and there on other tasks when my aganda open some room for it. :smile:
