### ISSUE TITLE
OFN BE : loading of the page "Products" without result

### ISSUE THREAD

**Issue by SophieDuponcheel** [openfoodfoundation/openfoodnetwork#6608]
## Description

When I go to consult the products in a entreprise's product catalog (example: coprosain s.c) or even in the product tab, the page is loading but the products never appear. I can see the first 15 products, then to see the next 50 on the load page but nothing appears.

This has no impact on the online shop but the producers don't know how to modify their product anymore, which is really problematic.

## Expected Behavior

see all the products and be able to modify them

## Actual Behaviour

the page is loading but the products never appear. 

## Steps to Reproduce

1. I go to the dashboard of the coprosain s.c. entreprise, I want to change a product. I go to the "product" tab. I can see the first 15 products, then to see the next 50 on the load page but nothing appears.
2.
3.
4.

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/63047606/103660288-b4e70280-4f6d-11eb-8139-1cd8758b3d51.png)

Error 422 on https://openfoodnetwork.be/api/products/bulk_products.json?import_date=&page=1&per_page=15&q[name_cont]=&q[primary_taxon_id_eq]=&q[s]=&q[supplier_id_eq]=116

## Severity
 bug-s2

## Your Environment
 i'm using a PC, with mozilla firefox

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

**Comment by SophieDuponcheel** [comment]
No, they are also sold on Coquelicoop shop. In fact, they are the ones who warned me of the problem. When I try with another company, the problem doesn't exist. It's only the coprosain products that are the problem (for the moment).

**Comment by Matt-Yorkley** [comment]
Okay, this looks like another occurrence of the variant unit_value / `NaN` issue...

**Comment by Matt-Yorkley** [comment]
Interestingly I can clearly see there's an error occurring here, but it doesn't show up in Bugsnag, and I can reproduce it. :thinking:

**Comment by Matt-Yorkley** [comment]
Okay, this is not the same bug as the other variant unit issues...

**Comment by Matt-Yorkley** [comment]
The serializer is throwing this error: `exception: "868: NaN not allowed in JSON"`, but none of the fields on that object or related objects are invalid or `NaN`...?

**Comment by Matt-Yorkley** [comment]
When I try to write specs for this in master, I can't replicate the issue. I think there may have been a bug in JSON parsing of `NaN` values, but it seems like it's fixed with Ruby 2.4.4?

**Comment by Matt-Yorkley** [comment]
Let's check this again after the next release is deployed...

**Comment by RachL** [comment]
Great, thanks @Matt-Yorkley !

**Comment by SophieDuponcheel** [comment]
@RachL @Matt-Yorkley  it's not solved if I understand correctly? The person who manages "coquelicoop" with "coprosain" products gets impatient, it blocks them too much. I don't know what to tell her. Sorry to rush you.

**Comment by Matt-Yorkley** [comment]
@SophieDuponcheel I think it will be solved when the next release is deployed.

**Comment by SophieDuponcheel** [comment]
it means the next tuesday? could you explain me why? so that I'm explaining to the users of "coprosain" products. For them it will surely be a too late answer but well ... thank you to help us !!

**Comment by RachL** [comment]
@SophieDuponcheel we only deploy on Tuesdays, we don't have the capacity to do more frequent releases at the moment. It involves time on the dev team to prepare and deploy and time on testing that every thing is ok. So currently we cannot do it more than once a week.

**Comment by Matt-Yorkley** [comment]
@SophieDuponcheel I've had another look, and I think it's fixed now in production (live).

**Comment by SophieDuponcheel** [comment]
but I have bad news, the problem persists with other producers. I just had a complaint for the shop "du pain & des roses" with the producer "La ferme de la tortue bio".

**Comment by SophieDuponcheel** [comment]
![Uploading image.png…]()

**Comment by SophieDuponcheel** [comment]
the user of "du Pain et des Roses" sent me this URL to explain the bug  : https://www.openfoodnetwork.be/api/products/bulk_products.json?import_date=&page=9&per_page=15&q%5Bname_cont%5D=&q%5Bprimary_taxon_id_eq%5D=&q%5Bs%5D=&q%5Bsupplier_id_eq%5D=

and this link : https://developer.cdn.mozilla.net/fr/docs/Web/HTTP/Status/422

**Comment by Matt-Yorkley** [comment]
@SophieDuponcheel Can you reply to them and ask them to set the weight at: https://openfoodnetwork.be/admin/products/chicons-6/variants/10915/edit

I'd have done it myself, but it's not clear what the weight should be.

**Comment by Matt-Yorkley** [comment]
I'll close this for now, it should be resolved.
