### ISSUE TITLE
Products are not showed in the list for a specific producer

### ISSUE THREAD

**Issue by kabhotz** [openfoodfoundation/openfoodnetwork#6984]
## Description
After a bulk insert the product are not shown on the page:

https://stg.openfoodnetwork.it/admin/products

## Expected Behavior
When I select the producer "Antico Saponificio Salentino" as SuperAdmin in the products page and I press filter I have to see the products list.

## Actual Behaviour
When I select the producer "Antico Saponificio Salentino" as SuperAdmin in the products page and I press filter the spinning circle appear without notify me about any error and nothing happen.

Inspecting the page in the network tab I can see a status message 422 un processable entity that call the bulk import page:

https://stg.openfoodnetwork.it/api/products/bulk_products.json?import_date=&page=1&per_page=15&q%5Bname_cont%5D=&q%5Bprimary_taxon_id_eq%5D=&q%5Bs%5D=&q%5Bsupplier_id_eq%5D=90

No errors will appear on the page; I have tried also to check logs repeating the steps and I have this messages:

```
I, [2021-03-02 08:46:40#1893]  INFO -- : Started GET "/api/products/bulk_products.json?import_date=&page=1&per_page=15&q%5Bname_cont%5D=&q%5Bprimary_taxon_id_eq%5D=&q%5Bs%5D=&q%5Bsupplier_id_eq%5D=90" for 82.57.201.7 at 2021-03-02 08:46:40 +0100
I, [2021-03-02 08:46:41#1893]  INFO -- [Bugsnag]: Notifying https://notify.bugsnag.com of JSON::GeneratorError 
```

## Steps to Reproduce

1. Go to https://stg.openfoodnetwork.it/admin/products
2. Fill "PRODUTTORE" field with "Antico Saponificio Salentino" 
3. Press the filter button "FILTRA I RISULTATI"
4. The spinner circle will appear without provide any results

## Animated Gif/Screenshot

![image](https://user-images.githubusercontent.com/8977332/109616124-132afe80-7b35-11eb-8606-0bcd81772f85.png)

## Severity

bug-s2 (the producer affected can't work)

## Your Environment

* Version used: v3.5.6
* Browser name and version: any browser
* Operating System and version (desktop or mobile): any OS

## Possible Fix

Error message, or remove the wrong products form the import with an error message.

**Comment by RachL** [comment]
@kabhotz hello :) can you update to latest version? I think this should be fixed.

**Comment by kabhotz** [comment]
@RachL thanks for the suggestion!
I have updated the staging instance to check but unlucky the problem still persist.
I thinks that has been added some corrupted data in bulk import.

**Comment by RachL** [comment]
@kabhotz yes then you need to find in your database variants which have an empty unit_value. Maybe conversation here can help: https://github.com/openfoodfoundation/openfoodnetwork/issues/6737

**Comment by kabhotz** [comment]
Dear @RachL thanks for the suggestion it have solved my problem!
