### ISSUE TITLE
[Product import] Some products are duplicated instead of updated

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9494]
## Description
In the admin dashboard, if you import a file to update products, it can create duplicates for some products. Weirdly it seems to only apply to products which unit type is **ml (or mL)** and **quantity is between 688 and 703**. It's the same behavior whether you first create the product from the dashboard or from an import file.

It impacts hubs using csv imports to update their products database: they don't understand why certain products are created again, and they have to manually delete the duplicates and manually update the original products. 

> The investigation case was about two 700mL cachaça bottles. tchin tchin 🍹

## Expected Behavior
If you import a file to update products, the original products must be updated, not created again.

## Actual Behaviour
If you import a file to update products, it will create duplicates for some products (or variants): the ones between 688 and 704ml. In the Products tab, the exact same product (or variant) appears twice.

It doesn't seem to apply when using other unit types or other unit values.

## Steps to Reproduce
1. Connect to admin > Products tab > [Import tab](https://coopcircuits.fr/admin/product_import)
2. Click on "Browse"
3. Select a file with at least one of the product with  : 
703 ⩾ units ⩾ 688
unit_type = ml (or mL)
Ex. of test file : [test-weirdo.csv](https://github.com/openfoodfoundation/openfoodnetwork/files/9222271/test-weirdo.csv)

5. Just after the import, in the "Import validation overview", you see that all your products have been created. Save.
6. Click "Upload another file". Choose the same file. You will see that the products between 688 and 703mL will be created again, the other ones being updated.

### First import
![Screen Shot 2022-07-29 at 19 58 27](https://user-images.githubusercontent.com/28386648/181821817-ee776c59-de5e-45eb-b0eb-d8a0a2b67f18.png)

### Second import

![Screen Shot 2022-07-29 at 19 59 27](https://user-images.githubusercontent.com/28386648/181821839-d1055349-2536-4601-b065-083315ca1e96.png)

### Example of the dashboard product list with same products twice

![Screen Shot 2022-07-30 at 03 09 27](https://user-images.githubusercontent.com/28386648/181864587-ed7b57c9-55dc-468c-96b2-af3e4420ef81.png)

## Workaround
Each time you import a file to update your products database, you have to manually delete the duplicates and manually update the product if needed.

## Severity
bug-s3: a feature is broken but there is a workaround

## Possible Fix
When creating a 700mL product, the POST /admin/products request sends 
`name="product[unit_value]"
0.700000000000001` 

instead of 0.700

When importing the file to update the product, unit_value is not the same and the product is considered as new.

See difference in number formatting between requests for 687mL and 688mL: 
[whyohwhy.txt](https://github.com/openfoodfoundation/openfoodnetwork/files/9224067/whyohwhy.txt)

This probably has more consequences, as all products created between 688 and 703mL will have a wrong unit_value in database...For example an export of the product database would have to be manually corrected.

**Comment by jibees** [comment]
I tried to reproduce it on local (to see if somehow, I can fix it through the PR #9497) but I failed to reproduced it although it is super simple to see it in `fr-staging`

**Comment by audez** [comment]
@jibees I tested the import of the same file again in prod, and the issue is still here (file :
[test-weirdo(1).csv](https://github.com/openfoodfoundation/openfoodnetwork/files/9446829/test-weirdo.1.csv)
)

**Comment by audez** [comment]
yep the bug is still on staging and prod

**Comment by abdellani** [comment]
Hi

I was not able to reproduce the problem. The screenshot shows the third attempt to import your file.
![image](https://user-images.githubusercontent.com/16113997/197150771-c550aeff-bc8f-47e6-ab0e-b6aee06fe30e.png)

Also, I couldn't see any problem with the product table. Except for some values (693 converted to 693.0000000000001)

![image](https://user-images.githubusercontent.com/16113997/197151091-932eff06-e8d0-4a57-9951-ff07114fd584.png)

**Comment by RachL** [comment]
thanks for your time on this @abdellani perhaps the underlining issue is fixed then. Let's close it and reopen if we manage to reproduce it.

**Comment by audez** [comment]
@abdellani thank you! I just tested and unfortunately the issue is still here 😢

To reproduce:
- Create two products from the admin interface (/admin/products), for instance:
701ml product, category "ALCOOL FORT", units: 701ml, TVA 20%
704ml product, category "ALCOOL FORT", units: 704ml, TVA 20%

- Then import a csv file to update these 2 products (
[test-weirdo4.csv](https://github.com/openfoodfoundation/openfoodnetwork/files/9837426/test-weirdo4.csv)

- The 704ml product is updated, but the other is created again 
![Screen Shot 2022-10-21 at 10 56 07](https://user-images.githubusercontent.com/28386648/197156803-ead386a4-9192-4c34-824a-12dbbc02ad40.png)

But you're right that the bug doesn't exist anymore if you created the product the first time by importing a file. But it's not sorted out, it's just because they're imported twice with the wrong formatting, so for the system it's the same product.
We can see as you said that the products between 688 and 703ml are still badly formatted:
![Screen Shot 2022-10-21 at 10 48 35](https://user-images.githubusercontent.com/28386648/197157711-2142f540-3c8f-45c3-8700-c46eab358f02.png)


The fix would be: when importing a product from a csv file, remove the formatting of products between 688 and 703ml.

**Comment by RachL** [comment]
> The fix would be: when importing a product from a csv file, remove the formatting of products between 688 and 703ml.

@audez I don't think that should be the role of the product import? If I understand clearly the problem is at the product catalog level? Otherwise can you detail how the second 704ml product was saved with manual creation and then with product import?

**Comment by audez** [comment]
Maybe I formulate it poorly. This is what I wanted to say: there is a bug to be corrected: when you import products **only from 688 and 703ml** with a .csv file, the products unit are recorded with a bad formatting. 
For instance you import a product, in the request it is "units":"701", but when you see the products in the product list, it displays 701.0000000000001. And in the db it is recorded as 701.0000000000001.
There is no problem if you update this product by re-importing a .csv file, because it will compare  701.0000000000001 to 701.0000000000001, and it will be considered as the same product. But still the unit is wrong.

Now this bug doesn't exist when creating products from the interface. So if you create a product from the interface, whether within or outside 688 to 703ml range, the units are good (701 will be displayed as 701). 

But then if you import a .csv to update these products in the 688 to 703ml range that you created by hand, it will create a new product, as the imported product will be recorded as X.0000....01 and considered new.

For 704ml products, there is no problem, whether by importing or creating from the interface, because the bug is only from 688 to 703ml.

If it was a problem at the product catalog level, you would probably see X.0000....01 for both products created by hand or imported with .csv

That's why I guess the thing to check is: how the product is recorded in the db after a product import, because there's something wrong with the unit formatting, weirdly only for numbers from 688 to 703 and mL unit

**Comment by audez** [comment]
When I created the issue, the bug was both when creating from the dashboard or importing. But this summer after @jibees did some fix it was sorted out when creating from the dashboard, but remained when importing csv.

**Comment by RachL** [comment]
ah ok thanks for the additional info! @abdellani do you have enough info to move forward?

**Comment by abdellani** [comment]
Yes @RachL .
You can assign it to me now : )

**Comment by jibees** [comment]
@abdellani done! and thanks! 🙏

**Comment by abdellani** [comment]
Here's what I found so far.
When I tried to create an invalid product with the unit_value = 700, the value was converted to 699.9999999999999 at the view level.
When I changed the unit from "mL" to "L", the unit value problem doesn't occur. 

I think the problem is related to string-to-float conversion in javascript (when it tries to convert 0.7  in product.master.unit_value). 

I'm not familiar with AngularJs, but I suspect that the problem is somewhere around `app/assets/javascripts/admin/products/controllers/edit_units_controller.js.coffee`

![image](https://user-images.githubusercontent.com/16113997/197491343-83235a5d-e1c7-4d3d-a5d6-0267f202cbab.png)

I'll continue on it later.

**Comment by abdellani** [comment]
I found a  problem at the controller level: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/admin/products/controllers/units_controller.js.coffee#L39

When the controller initializes the visible `value` field in the form (`unit_value_with_description`), The code devises the unit_value by the unit_scale.

- the unit_value = 0.7 (I guess values in  mL are automatically converted to L)
-  if the unit size is `ml`, the unit_scale will be equal to 0.001 ( [reference](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/admin/products/services/variant_unit_manager.js.coffee#L21))

I tried to do this in the console on the developer tools, and here is what I found:
```js
>0.7/0.001
699.9999999999999
```

I think there is a similar problem in the part of code that list the products.

@jibees  Should I create a PR to fix this problem?

**Comment by jibees** [comment]
Hi @abdellani 👋 
Thanks a lot for spotting this one!

Yes, we're facing this kind of issues and seems to using `js-big-decimal` is probably the good way to go. 
You can see an example here: https://github.com/openfoodfoundation/openfoodnetwork/pull/9497

Feel free to open a PR, thanks a lot for that!

**Comment by abdellani** [comment]
@jibees  
What should be the precision of the results? 2 digits as in this [example](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/admin/products/controllers/variant_units_controller.js.coffee#L29)?

**Comment by abdellani** [comment]
Hi
It seems that floating number precision problem is not only in the product creation form, it's also in the import function:
![image](https://user-images.githubusercontent.com/16113997/199682418-d561854d-29d7-4c9a-b656-acefec35ef0c.png)

I imported [test-weirdo4.csv](https://github.com/openfoodfoundation/openfoodnetwork/files/9926876/test-weirdo4.csv)

![image](https://user-images.githubusercontent.com/16113997/199682534-2a78d4f5-ea65-4589-af56-0e97806de9a3.png)

![image](https://user-images.githubusercontent.com/16113997/199683012-ffc66270-cc9c-453b-b135-ea3a745c9707.png)

![image](https://user-images.githubusercontent.com/16113997/199684818-672a7662-934a-4014-a68c-9f4aef68f222.png)

This is just an update, I'll handle the problem.

**Comment by abdellani** [comment]
Hi

The second part of the problem is in the [Unit Convert](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/product_import/unit_converter.rb#L64) used in the product imported.
```
[2] pry(#<ProductImport::UnitConverter>)> @attrs['units']
=> "701"
[3] pry(#<ProductImport::UnitConverter>)> @attrs['variant_unit_scale']
=> 0.001
[4] pry(#<ProductImport::UnitConverter>)> @attrs['units'].to_f * @attrs['variant_unit_scale']
=> 0.7010000000000001
```
Solution, use BigDecimal (`to_d`)
```
3.0.3 :009 > "701".to_f * 0.001
 => 0.7010000000000001 
3.0.3 :010 > "701".to_d * 0.001
 => 0.701e0
3.0.3 :011 > 0.701e0.to_s
 => "0.701" 
```
