### ISSUE TITLE
[Admin] [Products] Missing/wrong translations 

### ISSUE THREAD

**Issue by audez** [openfoodfoundation/openfoodnetwork#9509]
## Description
In Admin > Products, two strings are displayed in French, they should be translated to English. 
The French translation of the "Par défaut" button is incorrect. 

## Expected Behavior
"Colonne" button must be translated to "Columns".
"Par défaut" button must be translated by "Save" in English, and "Sauvegarder" in French.

## Steps to Reproduce
1. In the Admin dashboard, go to Products page.
2. Click the "Colonnes" button

## Animated Gif/Screenshot
![Screen Shot 2022-08-03 at 11 53 02](https://user-images.githubusercontent.com/28386648/182580505-cda40e5b-5986-440a-b012-0a868b8ba786.png)

## Severity
bug-s4: it's annoying, but you can use it

**Comment by krishnasingh001** [comment]
Hi @audez 
It looks like this issue is resolved. 
![image](https://user-images.githubusercontent.com/61962822/187048516-72d0ff03-6b66-47a6-8739-56a84f991916.png)

**Comment by audez** [comment]
Awesome, thanks @krishnasingh001 ! I can't see the change on coopcircuits.fr, but I guess it's because we didn't do the last updates as the other instances

**Comment by drummer83** [comment]
Reopening, because still not fixed: https://github.com/openfoodfoundation/openfoodnetwork/pull/11627#issuecomment-1757883127

**Comment by drummer83** [comment]
Also the messages `Saving`and `Saved`(when clicking the button to save as default) are not being translated.
![image](https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/e5a09681-cce0-4b97-a500-b602f9251cef)

**Comment by RachL** [comment]
I think this is fixed now

<img width="288" height="442" alt="Image" src="https://github.com/user-attachments/assets/a5eed25b-1037-457f-bad7-082f4eba3f1d" />
